version: '3.8'

services:
  backend:
    build:
      context: ./htdocs/news-app-backend
      dockerfile: Dockerfile
    container_name: laravel_backend
    ports:
      - "8000:80"
    volumes:
      - ./htdocs/news-app-backend:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./htdocs/news-app # Adjust path to your React project
      dockerfile: Dockerfile
    container_name: react_frontend
    ports:
      - "5000:5000"
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: my_database
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
